
/*Moderate Problem Statements:

1. Retrieve the total number of customers in the database.
2. List all product names and their corresponding unit prices.
3. Calculate the total revenue generated from each product.
4. Find the top 5 customers who made the highest total purchases.
5. Calculate the average quantity of products ordered.
6. List all orders made in the year 2022.
7. Calculate the total discount given across all orders.
8. Count the number of orders placed by each customer.
9. Calculate the total revenue for each year.
10. List the names of employees hired in 2021 and their positions.
11. Calculate the average salary of employees hired in the last two years.
12. Retrieve the orders with a discount higher than 10%.
13. Calculate the total revenue and average revenue per order.
14. Find the products that were never ordered.
15. List the names of employees who have a salary above the average salary.
16. Calculate the total revenue for each product category (e.g., Sedan, SUV).
17. Retrieve the orders placed by customers with the last name 'Smith'.
18. Calculate the average discount applied to orders.
19. Find the top 5 employees with the highest salaries.
20. List the products ordered by each customer.

Advanced Problem Statements:

21. Calculate the total revenue for each quarter of the year.
22. Retrieve the customers who have not placed any orders.
23. Calculate the average salary change for employees who changed positions.
24. List the products that have never been ordered and the reason why.
25. Find the customers who made the highest purchase in each year.
26. Calculate the percentage of total revenue generated by each product.
27. List the employees who have never changed positions.
28. Calculate the cumulative salary expense for each department over time.
29. Find the customers who placed orders in consecutive months.
30. Calculate the average salary of employees for each department.
31. List the employees who changed positions more than once.
32. Calculate the standard deviation of salaries within each department.
33. Find the customer who made the highest purchase in a single order.
34. Calculate the average number of products ordered in each year.
35. List the employees whose salary has increased by more than 20%.
36. Find the customers who placed orders for all available products.
37. Calculate the total revenue for each product, including and excluding discounts.
38. List the employees who have been with the company for more than 2 years.
39. Calculate the median salary for employees in each department.
40. Find the employees whose salary is above the 90th percentile.
41. Calculate the average salary change for employees in each year.
42. List the products that have been ordered by at least 3 different customers.
43. Find the employees who have held the same position for more than 3 years.
44. Calculate the coefficient of variation of salaries within each department.
45. List the orders placed by customers whose last name starts with 'J'.
46. Find the products that have been ordered by customers from at least two different countries.
47. Calculate the total revenue for each product category within each year.
48. List the employees who were hired in the same year as their supervisor.
49. Find the customers who placed orders in three consecutive months.
50. Calculate the average salary of employees who changed positions within the last year.
*/